Update sr_common for shared-memory slot attribute
Otherwise a number of the unit tests fail since the shared-memory attribute
is unknown, e.g. from
https://launchpad.net/~myapps-reviewers/+snap/review-tools/+build/1632720/+files/buildlog_snap_ubuntu_bionic_amd64_review-tools_BUILDING.txt.gz

======================================================================
ERROR: test_verify_snap_declaration_empty (test_sr_declaration.TestSnapDeclarationVerify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/review-tools/parts/review-tools/build/reviewtools/sr_declaration.py", line 1454, in verify_snap_declaration
    SnapReviewDeclaration._verify_declaration(review, base_decl, base=True)
  File "/build/review-tools/parts/review-tools/build/reviewtools/sr_declaration.py", line 587, in _verify_declaration
    alt, decl, key, iface, index, allowed, (len(alternates) > 1)
  File "/build/review-tools/parts/review-tools/build/reviewtools/sr_declaration.py", line 339, in verify_constraint
    malformed(bn, "unknown attribute '%s'" % attrib, base)
  File "/build/review-tools/parts/review-tools/build/reviewtools/sr_declaration.py", line 254, in malformed
    raise SnapDeclarationException(err)
reviewtools.sr_declaration.SnapDeclarationException: "base declaration malformed (unknown attribute 'shared-memory')"

Signed-off-by: Alex Murray <alex.murray@canonical.com>